---
# vars file for quay-ansible

# @var QUAY_IMAGE_VERSION: "quay.io/redhat/quay:v3.1.3" # The source and tag of Quay container
quay_container_name: "quay"
quay_image_version: "quay.io/redhat/quay:v3.2.0"

quay_http_port: 80
quay_https_port: 443
quay_config_port: 8443

# @var POSTGRES_CONNECTION_STRING: "host={{ QUAY_ENDPOINT }} sslmode=disable dbname={{ postgresql_quay_db }} user={{ postgresql_quay_user }} password={{ postgresql_quay_user_password }} statement_timeout=60000" # The connection string built with other variables
# POSTGRES_CONNECTION_STRING: ""

# ### Not currently used ###
# # postgresql_unix_socket_directories:
# #   - /var/run/postgresql
# # postgresql_service_state: started
# # postgresql_service_enabled: true

# # NFS based defaults
# #nfs_rpcbind_state: started
# #nfs_rpcbind_enabled: true

# # Docker defaults
# #docker_service_state: started
# #docker_service_enabled: true
# #docker_restart_handler_state: restarted
# #docker_package: "docker"
# #docker_package_state: present
