---
- name: Start quay in config mode
  podman_container:
    detach: yes
    restart: no
    name: "quay-config"
    privileged: yes
    published_ports: "{{ quay_config_port }}:8443"
    image: "{{ quay_image_version }}"
    command: "config {{ quay_config_password }}"
  tags:
    - quay-config

- name: "Go login to quay host on port {{ quay_config_port }}"
  debug:
    msg: "Login to {{ inventory_hostname }}:{{ quay_config_port }} using username quayconfig and password {{ quay_config_password }}"
  tags:
    - quay-config

- name: "Setup configuration options in quay config"
  debug:
    msg: "1) Select mysql database option. 2) Fill out the fields with the following data. Database Server = {{ inventory_hostname }}, Username = {{ mysql_user }}, Password = {{ mysql_password }}, Database Name = {{ mysql_database }}, SSL certificate can be left blank for testing"
  tags:
    - quay-config

- name: "Final config settings"
  debug:
    msg: "At a minimum configure Server Hostname ({{ inventory_hostname }}) and Redis hostname ({{ inventory_hostname }}). Then click Save configuration changes and make sure that the configuration is validated. Download the configuration file and save it at <think of something here>"
  tags:
    - quay-config

- name: Pause
  pause:
    prompt: Please follow the 3 previous tasks for configuration
