---
# - name: Start quay repository mirror worker
#   docker_container:
#     detach: yes
#     restart: yes
#     name: "mirroring-worker"
#     privileged: no
#     image: "{{ QUAY_IMAGE_VERSION }}"
#     volumes:
#       - "{{ QUAY_ROOT_DIR }}/config:/conf/stack:Z"
#     command: "repomirror"
#   tags:
#     - quay-worker

- name: Start quay repository mirror worker
  podman_container:
    detach: yes
    restart: yes
    name: "mirroring-worker"
    privileged: no
    image: "{{ quay_image_version }}"
    volumes:
      - "{{ quay_root_dir }}/config:/conf/stack:Z"
    command: "repomirror"
  tags:
    - quay-worker
